id: I6EB7FD23
legacy_id: P010529
ocr_import_info:
  bdrc_scan_id: W23568
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T08:29:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:16:57.161368+00:00'
last_modified: 2022-09-02 09:17:51.813213
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23568
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23568
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་རྒྱ་ཆེན་པོ་ལྷན་ཅིག་སྐྱེས་སྦྱོར་གྱི་སྔོན་འགྲོའི་ཁྲིད་ཡིག
  author: ཁམས་སྤྲུལ ༠༣་ཀུན་དགའ་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.7486661646757657
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I2178:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2178
      total_pages: 732
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2178.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7731925965034215
    legacy_id: v001
  I2179:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2179
      total_pages: 678
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2179.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7239900922483999
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
