id: I6EB7FD23
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:33:23+00:00'
last_modified: '2022-06-08T14:16:44.239425+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23568
  title: ཕྱག་རྒྱ་ཆེན་པོ་ལྷན་ཅིག་སྐྱེས་སྦྱོར་གྱི་སྔོན་འགྲོའི་ཁྲིད་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B79B:
      image_group_id: I2178
      title: ''
      total_pages: 732
      order: 1
      base_file: B79B.txt
    F88B:
      image_group_id: I2179
      title: ''
      total_pages: 678
      order: 2
      base_file: F88B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
