id: P010529
initial_creation_type: ocr
source_metadata:
  id: bdr:W23568
  title: ཕྱག་རྒྱ་ཆེན་པོ་ལྷན་ཅིག་སྐྱེས་སྦྱོར་གྱི་སྔོན་འགྲོའི་ཁྲིད་ཡིག
  author: ''
  volumes:
    cd32a2bd08d6466e90265f6635c41f46:
      image_group_id: I2178
      title: ''
      volume_number: 1
      total_pages: 732
      base_file: v001.txt
    686c7b8fbfac47e0b23df7cf8c264d40:
      image_group_id: I2179
      title: ''
      volume_number: 2
      total_pages: 678
      base_file: v002.txt
